docker:
  image: yegor256/java8
decrypt:
  gradle.properties: "jb-hub-client/scrt/gradle.properties.asc"
  secring.gpg: "jb-hub-client/scrt/secring.gpg.asc"
install: |
  sudo curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh
         | sudo bash
         | sudo apt-get install git-lfs
         | git lfs install
         | git lfs pull
architect:
- smallcreep
merge:
  script: |
    ./gradlew clean build -PQuality -PIntegration --scan --info
    ./gradlew clean
deploy:
  script: |
    ./gradlew clean build -PQuality -PIntegration --scan --info
release:
  script: |-
    ./gradlew clean build upload -PPublish -PVer=${tag} --scan --info