language: java
sudo: required
script:
- "./gradlew clean build -PQuality --scan --stacktrace"
jdk:
- oraclejdk8
before_install:
- curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh
  | sudo bash
- sudo apt-get install git-lfs
- git lfs install
- git lfs pull
- chmod +x gradlew
- echo $failsafe.hub.username
- echo $username
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: VJzgnEwEH1LU4h5/Jo3p3Yh+p9ST0spTbhkcZ2H5lR9nS0nRb5pXBhfF00dkKMjfMZhp5kgcZwcHlnrmGEPd4Vz51leQLdNaRmvb3YgtMVF9RT4XjpquugvdDAxKfkRsynf/jCtIyLjHbyQkYZ/kb9Jqj9Ffl2smmh8U3jBElTK48VXa8As86GLX7rbhEOc4/EOOr/FfWTVLmG8DpxN6OYlhi/mBvXR/P3Ldrn8+qqzcyKdt4tBpQS8dtGmLtts1fMxupjk+X01Js5gt1cosk33EkoChPHBJN9KcFJ+0H1kROYYq3QGTxqN8CTG5ZcQGtdCfaNJ/GOgSSmnwO0Cjs8zEuQjoAQXJcUlzD4UrrBFBOXADdPOL4aQ6lmOvmTrEkGUd6WyE1x0K8epBnCrFBy9wS3sk7u428U0AMFOkoc3DaUknb6NaDD7mPWuATgceDdS08h2wxafvF3qsrdQzYUosF/hgT47rghQqx+pUMep9I3KvLIRObCW2t3PM6DcyHdL124gu7a3c5E0FD99W3JnacfMOTEtof1FrmGgQgqFLwqIGtsbs13fOgF3vOWAgDL5iot/SRto5ZegoYEQfBF9VINPNqkg414MOyTn8d+q7NaKLwS/hV7gzu7J9wkRYH+oF4zDUT9eI4Y2sbUinhrAapWLrI8v1GullajK7Jo0=
  - secure: mpwRWUM7SX0Y9gU2RaQiOjLYcytP4DrvXk7poEphjSXw4xMPnal7M4g+OEo1f87Y8whVUu7Yr8MIBzzRAK7dIvo3ffoMgcaqKqH71M7m9Q2BU2tU3hzMhE/KvDWOUV7KJh0BrbMB31Wu4rwP4p3sAxTxUeqBaoJMIlk2Q/6x4lG4ey4DASdWFbfQhJl5zkf/du4zumN3yMFh6VGq72QESlSCzw4qA45Fa8J7i5jL49ZN6Kj79m0W2o3KzKqSBcRMtVtki+PBo3D3eqfOC5XgTVyoC9+WzHe6MSiOul9yBn3Zyf35e2ARNStdraNznG1GvOn8G/W/Mxx24TGVtf495ntr52I6MGeo7GhUjrMOh7mSIUX9z2ITy+vT3PMtCHjG0+NQ7j9s+8ryzGfguc6hOlUG/hWTRjWpvF4iQsFKA1e3/tzMiA8Qt2DT9Cpw5p9/4pJ7lONDeBJrIDvcqB2QEOms24VGDH/aWwTASbFR9nK57b+eRM3q5TEWpQJVR/t0I0KbhsWdlBzqtU4fBVMIrII9lWxhx8jT0RZYhLnSl8nI6o2RAhjm06YOU8bWFcImxDtLxJdGQkxBuYZi0LdPV3RBOua0/eSS08+Sbp5ZiIKtgFaZ1Qa7M07YtvJwrMJ4INPCwlArf3y2XkyZoAV9z7lbwmLcYHoXv9jGFpDeP+0=
  - secure: M4f0U1Uj/MFEJ0LenGB23JAXc/mph0usOClByiBMtuCd+i8SBBSm8JM7/cBm2Wjq23DWKNzj0cnzIMT50cGM9Kuz4Z2WyScvktbn+h2NjPFVNXT5KwaKaTNmydyXyYPvIkm9+wKtxvXQgJmrwYDxuJguBr/JIKhwjB1j/dD3k0CF0Om41LvihaTsco6cuLZmQMm1Qo3z/XVws2mqlYvXg2ypp60gnQBCucLqrUX/di9BTGc2FpXLGjWcvqBm+AKbXoEpk2EY/2fiRT7qZ13xLsJthEtmoNr3SDHcwdHIVAzv8SeMVEHO8Bh1BhSO+P7cpmdAMxtOCvPKSfnvIY56ytjYTUGPouDHQKrG0beQ0hYS8g+tK6vLT2pDPShdtVbNQnfHNiMax21wr6rHLtetyrs5d5zUOBrH0104/sULo6MirjnQzHgsrcYAw7jJ4nagolJPd9CQDVQPJuRluXLFJioAe7ywxO+9oNJIQzqwafk0ySn08amnrYzTYDPQHXte1CGETgjiGXhipJy0xVKN7rNfERWLLTHmTXXKhKRbaA/ZLua1qRmuNXtBAH3Ofc1Cuwvnwyre6xsp/Ut2fXuFlQ0uTG3CUCcsfUOn3QTnwoyjvw5CcpEYnvH49GFZXpZEbWeChi58x2NbzMBi86/5VlJxL/Lz2xvGqiQdNWxjAAw=
