version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
install:
  - ps: |
        (new-object System.Net.WebClient).DownloadFile('https://github.com/git-lfs/git-lfs/releases/download/v2.1.1/git-lfs-windows-2.1.1.exe', 'git-lfs-2.1.1.exe')
        msiexec /i git-lfs-2.1.1.exe /quiet /qn /norestart /log install.log
  - cmd: java -version
  - cmd: git lfs install
  - cmd: git lfs pull
  - cmd: (if not exist "%USERPROFILE%/.gradle" mkdir "%USERPROFILE%/.gradle") && (echo. >> "%USERPROFILE%/.gradle/gradle.properties" && echo org.gradle.daemon=false >> "%USERPROFILE%/.gradle/gradle.properties")
build_script:
  - gradlew.bat clean assemble --info --scan
test_script:
  - gradlew.bat clean check --info -PQuality -PIntegration --scan
cache:
  - C:\Users\appveyor\.gradle